dist: focal

language: python

matrix:
    include:
        - python: 3.7
          os: linux
          env: BUILD_COMMAND=bdist_wheel

        #- language: generic
        #  os: osx
        #  env: 
        #      - BUILD_COMMAND=bdist_wheel
        #      - PYTHON_VERSION=3

        - python: 3.8
          arch: ppc64le
          os: linux
          env: BUILD_COMMAND=sdist

branches:
    only:
        - master

cache:
    apt: true

before_install:
    # On MacOS: install python3 if needed
    - source ./ci/travis_osx.sh

install:

    # Upgrade distribution modules
    
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools

    # Install build dependencies
    - pip install --upgrade wheel
    - pip install --upgrade numpy

    # Print Python info
    - python ./ci/info_platform.py
    - pip list

    # Generate source package or wheel
    - python setup.py $BUILD_COMMAND
    - ls dist

script:
    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - pip install --upgrade pip

    # Install from source package
    - |
      for filename in dist/fisx*.*; do
        echo "\nInstall $filename"
        pip install --pre $filename $PIP_INSTALL_EXTRA_ARGS
      done

    # Print Python info
    - python ci/info_platform.py
    - pip list

    # Run the tests
    - python -m fisx.tests.testAll
