[build-system]
requires = [
    "setuptools",
    "wheel",
    "oldest-supported-numpy; python_version< '3.9'",
    "numpy >= 1.23; python_version >= '3.9'",
    "Cython"
]
build-backend = "setuptools.build_meta"
