# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }} ${{ matrix.name-suffix }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name-suffix: "(Minimum Versions)"
            os: ubuntu-latest
            python-version: 3.7
            BUILD_COMMAND: sdist
          - name-suffix: "sdist"
            os: ubuntu-latest
            python-version: 3.8
            BUILD_COMMAND: sdist
          - name-suffix: "bdist_wheel"
            os: macos-latest
            python-version: 3.8
            BUILD_COMMAND: bdist_wheel

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Display the python version
      - name: Display Python version
        run:
          python -c "import sys; print(sys.version)"

      - name: Upgrade distribution modules
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install build dependencies
        run: |
          pip install --upgrade wheel
          pip install --upgrade numpy

      - name: Print python info
        run: |
           python ./ci/info_platform.py
           pip list

      - name: Generate source package or wheel
        run: |
          python setup.py ${{ matrix.BUILD_COMMAND }}
          ls dist

      - name: Install from source package
        run:
          for filename in dist/fisx*.*; do
            echo "\nInstall $filename"
            pip install --pre $filename
          done

      - name: Run the tests
        run:
          python -m fisx.tests.testAll
